apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalabit-api
  namespace: scalabit
  labels:
    app: scalabit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalabit-api
  template:
    metadata:
      labels:
        app: scalabit-api
    spec:
      containers:
        - name: scalabit-api
          image: europe-west2-docker.pkg.dev/mystic-shelter-468310-a2/scalabit-repo/scalabit-api:e733c765e0b142b5ae42101ac827490a7056ba33
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080